# PREDICT THE MEAN

In [2]:
# The basics
import numpy as np
import pandas as pd

# Cross validation and model selection
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV

# Models
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

# Plotting
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import matplotlib.transforms as mtransforms
import matplotlib.ticker as ticker
import matplotlib.pylab as pl

from plot_actual_vs_pred import plot_actual_vs_pred

# Looping
import itertools

In [3]:
sensor = pd.read_csv('../../data/sensor1.csv')

In [4]:
sensor.head(10)

exposure    NO   NO2   NH3  0.05-1-slope-0  0.05-1-slope-1  0.05-1-slope-2  \
0       1.0  10.0   5.0  20.0      -18.855169      -28.289268       -0.390916   
1       1.0  10.0   5.0  20.0      -28.979886       -9.251672       -0.247580   
2       1.0  10.0   5.0  20.0      -25.431240      -12.874158       -0.221519   
3       1.0  10.0   5.0  20.0      -30.126572       -8.196200       -0.260610   
4       2.0  20.0  40.0  40.0      -19.506695      -27.051368       -0.456068   
5       2.0  20.0  40.0  40.0      -25.357400      -13.043555       -0.469099   
6       2.0  20.0  40.0  40.0      -27.557387      -10.983646       -0.524479   
7       2.0  20.0  40.0  40.0      -26.569239      -12.027174       -0.338794   
8       3.0  40.0  40.0  80.0      -20.431862      -26.334690       -0.390916   
9       3.0  40.0  40.0  80.0      -29.214435       -9.342886       -0.286672   

   0.05-1-slope-3  0.05-1-slope-4  0.05-1-slope-5  ...  2500.0-1-avg-230  \
0       -0.234549       -0.143336        0.026061  ...         36.095859   
1       -0.169397       -0.218261        0.061895  ...         36.115405   
2       -0.234549        0.026061       -0.312733  ...         36.163183   
3       -0.091214       -0.130305       -0.182427  ...         36.170784   
4       -0.403946       -0.208488       -0.256267  ...         35.955781   
5       -0.130305       -0.221519       -0.026061  ...         35.939493   
6       -0.065153       -0.156366       -0.117275  ...         35.942750   
7       -0.195458       -0.130305       -0.026061  ...         35.949266   
8       -0.351824        0.013031       -0.221519  ...         35.929720   
9       -0.221519       -0.156366        0.026061  ...         35.946008   

   2500.0-1-avg-231  5000.0-1-avg-232  5000.0-1-avg-233  5000.0-1-avg-234  \
0         36.118662         35.978584         35.880855         35.880855   
1         36.144723         35.978584         35.962296         35.919947   
2         36.141466         35.962296         35.926462         35.916689   
3         36.164269         36.076313         35.978584         35.946008   
4         35.929720         35.805930         35.760323         35.711458   
5         35.916146         35.803487         35.704943         35.691913   
6         35.884113         35.763581         35.698428         35.722046   
7         35.916689         35.815703         35.734262         35.727747   
8         35.900401         35.789642         35.737519         35.682140   
9         35.974512         35.802672         35.724489         35.721231   

   5000.0-1-avg-235  5000.0-1-avg-236  5000.0-1-avg-237  5000.0-1-avg-238  \
0         35.867825         35.874340         35.825476         35.840135   
1         35.899858         35.910174         35.861309         35.884113   
2         35.910174         35.906916         35.903659         35.913432   
3         35.942750         35.910174         35.933792         35.939493   
4         35.688655         35.685397         35.675624         35.685397   
5         35.701686         35.704943         35.701686         35.691913   
6         35.695170         35.685397         35.688655         35.698428   
7         35.714716         35.678882         35.708201         35.688655   
8         35.717974         35.714716         35.688655         35.678882   
9         35.698428         35.688655         35.691913         35.689469   

   5000.0-1-avg-239  
0         35.845021  
1         35.869996  
2         35.900401  
3         35.900401  
4         35.665852  
5         35.698428  
6         35.675624  
7         35.708201  
8         35.656079  
9         35.688655  

[10 rows x 484 columns]

## Regression on all exposures

In [9]:
# Independent variables - shape features
X = np.asarray(sensor.iloc[:, 4:])

# Dependent Variables - gas concentrations
Y = np.asarray(sensor.iloc[:, 1:4])
# Train test split
X, X_val, Y, Y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

31.0


In [11]:
Y_val.shape

(300, 3)

In [15]:
# Predicting on unseen validation data
Y_mean = np.mean(Y)
Y_pred = np.full(shape = Y_val.shape, fill_value = Y_mean)
print(Y_pred)
# Plotting actual vs. predicted
# Information to display
RMSEs = np.round(mean_squared_error(Y_val, Y_pred, squared=False, multioutput = 'raw_values'), 3)

info = [f'RMSE = {RMSEs[i]}' for i in range(3)]
plot_actual_vs_pred(Y_val, Y_pred, 'OLS - EXPOSURES WITH ALL FEATURES', info) 

[[30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667 30.94166667]
 [30.94166667 30.94166667